#property copyright  "Copyright 2013-2015, Vasiliy Sokolov, St.Petersburg, Russia."
#property link      "https://login.mql5.com/ru/users/c-4"
#property version   "1.12"
#define VERSION "HedgeTerminal 1.12"
#property description "HedgeTerminal is designed for hedging net positions in MetaTrader 5 and for simple control over expert advisors."
#property description "ULTIMATE edition - full-featured version without symbol and history limits."
#property icon ".\\img\\HedgeTerminalUltimate64x64.ico"
#include "HedgeTerminal.mqh"